### ISSUE TITLE
80244008 error on Vista Home Premium 64-bit!

### ISSUE THREAD

**Issue by Trancer03** [LegacyUpdate/LegacyUpdate#132] opened 2023-03-08 20:41 UTC
I get an error while trying to check for updates on Vista Home Premium 64-bit:
**80244008** SOAPCLIENT_PARSEFAULT_ERROR - SOAP client failed to parse a SOAP fault.

**Comment by 911delorean** [comment] 2023-03-10 22:39
I am having the exact same error. I am running Server 2008 R1 Enterprise. I ran both Legacy Update and the built in Windows Update client and both got the same error code 80244008.

**Comment by kirb** [comment] 2023-05-11 08:01
Not sure if this is the same as the problem the first two posters were having, but this has been coming up a bit more frequently lately as noted by some people on the Discord.

I think it might be a problem with my proxy server. I’ve seen it log some connection reset errors but I never looked into it properly. When it happens I believe I made it just pass an error straight back to the client, when really I should specifically handle it by trying the request again.

Specifically the custom proxy I wrote uses HTTP keep-alive with the upstream Microsoft server for best performance, so the TCP pipe stays open and can be reused for multiple requests. I have a feeling Microsoft’s server eventually decides I’ve kept the connection open for too long and closes it. The problem being it must cut the TCP connection without properly telling the client that it’s being closed, so the next request the proxy server makes will go into a void. The best workaround is for me to have it just try the request again.

**Comment by vichingo455-temp** [comment] 2023-09-05 17:27
Fix:
1. Open a cmd as administrator and type ``net stop wuauserv`` to stop Windows Update
2. Go to ``C:\Windows``
3. Delete the ``SoftwareDitribution`` folder
4. Try checking again

**Comment by kirb** [comment] 2024-10-24 07:12
Going to close this because it hasn't come up in a long time.

**Closed by kirb** 2024-10-24 07:12 UTC

**Comment by Trancer03** [comment] 2025-02-14 07:57
I've installed Windows Vista Ultimate SP 3 64-bit. The error came back!

**Comment by kirb** [comment] 2025-02-14 08:04
Ick sorry about that, is it consistent? As in, does it fix itself if you try checking for updates again, or does it always fail?

I might need to test what exactly Vista’s WU agent is expecting SOAP faults to look like. My server might be sending something it doesn’t understand.

**Comment by Trancer03** [comment] 2025-02-14 08:11
It's consistent!

**Comment by Trancer03** [comment] 2025-02-14 08:37
It worked this time!

**Comment by kirb** [comment] 2025-02-14 09:47
The cause was that the server ran out of space! Happened about an hour before your comment. Thanks heaps for bringing it up.

I’ve been meaning to redo the database used by the [stats](https://legacyupdate.net/stats) page. I [announced](https://discord.com/channels/1095995920409178112/1096005052918943745/1328251071797133383) what I was doing on Discord a few weeks ago, the migration to the new database is unfinished so rather than processing into the old database, I’ve just had the server writing reports to disk, then my local PC pulls them off every 10 mins. My PC crashed a few days ago and I forgot to start that script again, so whoops.

For anyone curious, the oldest report was from the 9th, and there were 69,148 of them! The script just spent about 30 mins pulling reports off. Currently I have 1.5GB worth of compressed reports, would be something more like 9GB uncompressed.
