### ISSUE TITLE
Legacy update dont work with other browsers

### ISSUE THREAD

**Issue by seba2282** [LegacyUpdate/LegacyUpdate#244] opened 2024-04-29 15:57 UTC
How in topic. After uninstall IE from example windows 7 and have Microsoft Edge, Legacy update don't work. Need again turn on IE. So logical it will not work on Windows 11 (how is as compatible), because that system haven't old IE.
Maybe fix? 

Best Regards

**Comment by seba2282** [comment] 2024-05-01 07:10
Thanks for informations. I tried on VMWare Windows 11 and Legacy Update and when i tried downloading by browser updates, still stopped the browser was hanging and wanted to turn it off only. So I don't know. Make new topic about that or someone will test on Windows 11? Me used home edition to tests.

**Comment by kirb** [comment] 2024-05-01 07:26
IE mode in Edge should work. The only limitation would be if you have group policies in force to block ActiveX.

The tab will freeze while the install dialog is open, that's expected. Sorry, that can’t really be fixed, it’s just how that dialog was implemented by Microsoft.

Going to close this because this seems to be a duplicate of #233, but you can still feel free to keep commenting here.

**Closed by kirb** 2024-05-01 07:26 UTC
