### ISSUE TITLE
STATUS_ILLEGAL_INSTRUCTION when running the setup binary on Cyrix hardware

### ISSUE THREAD

**Issue by SSUPII** [LegacyUpdate/LegacyUpdate#242] opened 2024-04-25 18:04 UTC
![Istantanea_2024-04-25_19-39-40](https://github.com/LegacyUpdate/LegacyUpdate/assets/42090377/49936878-d8aa-4435-a249-7fa0c4e39a88)
Setup is crashing with `STATUS_ILLEGAL_INSTRUCTION` (0xC000001D) as soon as it is opened on Windows XP Professional SP3 x86.

To make sure the file wasn't corrupted, I downloaded it twice and get the same error.

Hardware:
Freeway FW-6400GX
VIA Cyrix III 450MHz (Samuel)
256MB RAM
S3 Trio32

**Comment by kirb** [comment] 2024-04-26 02:28
Thanks for reporting! This is a duplicate of #220 so closing in favor of that. For now, you can use Legacy Update 1.7.1.

**Closed by kirb** 2024-04-26 02:28 UTC
