### ISSUE TITLE
Reboot loop on windows 7 after installing legacy update

### ISSUE THREAD

**Issue by MaxWorlds** [LegacyUpdate/LegacyUpdate#311] opened 2024-12-07 17:25 UTC
This is probably Sysprep mode
[VID_20241207_210937.webm](https://github.com/user-attachments/assets/e6c4029b-2527-4bf9-ac6e-841bb207f579)

**Comment by kirb** [comment] 2024-12-08 02:10
Thanks, will close this as a duplicate of either #285 or #307.

**Closed by kirb** 2024-12-08 02:10 UTC
