### ISSUE TITLE
Forced activation.

### ISSUE THREAD

**Issue by Ballagyr** [LegacyUpdate/LegacyUpdate#287] opened 2024-11-06 06:56 UTC
One thing I would like to report about the Legacy Update is this forced activation they do on Win7 and Vista systems. Even if I uncheck the activation option in the Legacy Update installer, when I restart Windows, it displays the message that the system has been activated. I did not request this, since I use another activation method, which does not use any software. The systems I installed on the VM were already activated, meaning there was no need to do it again.

I activate my Windows using a method that does not use any software, you can find out how this works by accessing the MS Guides website. The point here is, since I don't need any activation software, I would like the Legacy Update installer to not actually use this, since I always uncheck the activation option in that installer and even though I did that, he activate it.

I would like to know what activation method was used by Legacy Update, so that I can revert and make my system intact, as I do not want any type of crack installed on my system.

**Comment by kirb** [comment] 2024-11-06 07:21
**Legacy Update is not an activation crack.** Please see https://legacyupdate.net/faq/security for more info. It does say only XP, this is also true for Vista now, but the answer is mostly true for all versions in general.

If you close the activation wizard, nothing will happen to your system. It’s only a convenience that it opens it for you after the setup completes.

There are 2 bugs in 1.10 leading to what you experienced:

* Your selections are lost if Legacy Update needs to restart the system
* The check for activation state on Vista/7/8 seems to incorrectly detect as unactivated for some systems

I don’t know why either bug exists yet. The activation state one is more peculiar. The intended behavior is that the activation option only shows when unactivated, and of course that it only opens the activation wizard if you did tick that box.

I may still remove this feature because it’s just causing confusion. Or at least, revert it to only show on XP (and Vista now).

**Comment by seba2282** [comment] 2024-11-06 14:35
I have other problem, when I have unchecked Legacy Update in options, it is still installed to me. It is bug? I thought it should be optional component as only program, but roots or wu agent should be normally functional without that. Program only connect with Internet Explorer. Windows Update as Windows Update when is patched by some options legacy update, should work without separate legacy update program and when we disable internet explorer too.

**Comment by seba2282** [comment] 2024-11-06 14:44
Thanks for informations.

**Comment by kirb** [comment] 2024-11-07 03:18
The issue with the activation option being shown when the system is already activated applies to Vista - 8.1.

There is no manipulation/cracking/etc of activation, only a check for whether the system **is** activated. Legacy Update does not and never will mess with activation, that's not the purpose of this tool, and I wouldn’t want it to be either because that would put the entire project at risk. Your activation has not been affected whatsoever.

For anyone technical, you can confirm exactly what we’re doing here:

* Determining whether to show the checkbox: https://github.com/LegacyUpdate/LegacyUpdate/blob/93fdbe32f960f7dc135c7b4f1a0b9ecdbf607abe/setup/setup.nsi#L769-L779
* The logic that checks for activation on Vista - 8.1: https://github.com/LegacyUpdate/LegacyUpdate/blob/93fdbe32f960f7dc135c7b4f1a0b9ecdbf607abe/nsisplugin/IsActivated.c#L31-L67
* Opening the activation wizard: https://github.com/LegacyUpdate/LegacyUpdate/blob/93fdbe32f960f7dc135c7b4f1a0b9ecdbf607abe/setup/setup.nsi#L930-L939

Since there are 2 bugs here, I made #289 and #290 and I’ll close this.

**Closed by kirb** 2024-11-07 03:18 UTC
